"""strengthen relationships integrity and indexes

Revision ID: 1fb5dbb24f10
Revises: fc67c053635b
Create Date: 2026-09-14 19:56:12.618867

"""
from alembic import op
import sqlalchemy as sa


revision = '1fb5dbb24f10'
down_revision = 'fc67c053635b'
branch_labels = None
depends_on = None


ENUM_RENAMES = [
    ("project_status", "ACTIVE", "active"),
    ("project_status", "ON_HOLD", "on_hold"),
    ("project_status", "COMPLETED", "completed"),
    ("project_status", "ARCHIVED", "archived"),
    ("work_status", "TODO", "todo"),
    ("work_status", "IN_PROGRESS", "in_progress"),
    ("work_status", "BLOCKED", "blocked"),
    ("work_status", "COMPLETED", "completed"),
    ("work_status", "CANCELLED", "cancelled"),
    ("task_priority", "LOW", "low"),
    ("task_priority", "MEDIUM", "medium"),
    ("task_priority", "HIGH", "high"),
    ("task_priority", "URGENT", "urgent"),
    ("message_role", "USER", "user"),
    ("message_role", "ASSISTANT", "assistant"),
    ("message_role", "SYSTEM", "system"),
    ("message_role", "TOOL", "tool"),
]


def upgrade() -> None:
    for enum_name, old_label, new_label in ENUM_RENAMES:
        op.execute(f"ALTER TYPE {enum_name} RENAME VALUE '{old_label}' TO '{new_label}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_phases_task_status', 'phases', ['task_id', 'status'], unique=False)
    op.create_index('ix_projects_user_status', 'projects', ['user_id', 'status'], unique=False)
    op.create_index('ix_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_index('ix_tasks_user_status', 'tasks', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###

    op.create_check_constraint('ck_tasks_estimated_minutes_nonneg', 'tasks', 'estimated_minutes >= 0')
    op.create_check_constraint('ck_tasks_actual_minutes_nonneg', 'tasks', 'actual_minutes >= 0')
    op.create_check_constraint('ck_phases_order_index_nonneg', 'phases', 'order_index >= 0')
    op.create_check_constraint('ck_phases_estimated_minutes_nonneg', 'phases', 'estimated_minutes >= 0')
    op.create_check_constraint('ck_phases_actual_minutes_nonneg', 'phases', 'actual_minutes >= 0')
    op.create_check_constraint('ck_subtasks_order_index_nonneg', 'subtasks', 'order_index >= 0')
    op.create_check_constraint('ck_subtasks_estimated_minutes_nonneg', 'subtasks', 'estimated_minutes >= 0')
    op.create_check_constraint('ck_subtasks_actual_minutes_nonneg', 'subtasks', 'actual_minutes >= 0')


def downgrade() -> None:
    op.drop_constraint('ck_subtasks_actual_minutes_nonneg', 'subtasks', type_='check')
    op.drop_constraint('ck_subtasks_estimated_minutes_nonneg', 'subtasks', type_='check')
    op.drop_constraint('ck_subtasks_order_index_nonneg', 'subtasks', type_='check')
    op.drop_constraint('ck_phases_actual_minutes_nonneg', 'phases', type_='check')
    op.drop_constraint('ck_phases_estimated_minutes_nonneg', 'phases', type_='check')
    op.drop_constraint('ck_phases_order_index_nonneg', 'phases', type_='check')
    op.drop_constraint('ck_tasks_actual_minutes_nonneg', 'tasks', type_='check')
    op.drop_constraint('ck_tasks_estimated_minutes_nonneg', 'tasks', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_user_status', table_name='tasks')
    op.drop_index('ix_tasks_project_status', table_name='tasks')
    op.drop_index('ix_projects_user_status', table_name='projects')
    op.drop_index('ix_phases_task_status', table_name='phases')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    # ### end Alembic commands ###

    for enum_name, old_label, new_label in ENUM_RENAMES:
        op.execute(f"ALTER TYPE {enum_name} RENAME VALUE '{new_label}' TO '{old_label}'")