"""add completed_at to phases

Revision ID: 3a778672f513
Revises: 724642fd2a1b
Create Date: 2026-09-24 00:09:48.994514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a778672f513'
down_revision = '724642fd2a1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phases', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phases', 'completed_at')
    # ### end Alembic commands ###
